# Generated by Django 4.2.5 on 2023-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_certificate_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
