# Generated by Django 4.2.5 on 2023-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("question", models.TextField(max_length=400)),
                (
                    "priority",
                    models.CharField(
                        choices=[("L", "low"), ("M", "medium"), ("H", "high")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
