# Generated by Django 4.2.5 on 2023-10-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "The Question",
                "verbose_name_plural": "Peoples Questions",
            },
        ),
    ]
